server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project2?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/18th_project2_db?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: asd123456fnmj

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


pagehelper:
  helper-dialect: mysql
logging:
  level:
    com.baidu.mall.mapper: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.baidu.mall.typehandler
